name = "DefaultAgent"

[tools]
tools = ["serper", "wolfram", "wikipedia"]

[memory]
memory_type = "ConversationBufferMemory"
memory_key = "chat_history"
return_messages = true

[index]
indexes_available = []
retriever = []

[llm]
index_type = "ChatOpenAI"
temperature = 0.8
model_name = "gpt-4"

[prompt]
prompt = "Hello there you're golem!"